#!/usr/bin/env python

import sys, getopt, re, subprocess

def main(argv):

   f = open(argv[0])

   tasklines = [line for line in f.readlines() if re.match('^.*\*TASK\*', line)]

   for taskline in tasklines: 
       m = re.match('(^.*\*TASK\*)\s*(.*)$', taskline)
       task = m.group(2)
       print ('*TASK* ' + task)
       process = subprocess.run('task add ' + task, shell=True)
   

if __name__ == "__main__":
   main(sys.argv[1:])

